stages:
  - run

default:
  image: debian:12
  before_script:
    - apt update && apt install openssh-server openssh-client -y
    - ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -N ""
    - mkdir -p /run/sshd
    - /usr/sbin/sshd
    - ssh-keyscan -H localhost >> /root/.ssh/known_hosts
    - cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys

    - |
      cat <<EOF >.env.yml
      ---
      username: "ansible"
      domain: "localhost"
      email: "an@email.address"
      nextcloud_username: "admin_user"
      nextcloud_password: "admin_pwd"
      gitea_username: "admin_user"
      gitea_password: "admin_pwd"
      vaultwarden_password: "admin_panel_pwd"
      ssh_key: "~/.ssh/id_rsa"
      dotfiles_repo: "https://gitlab.com/ericdriussi/dotfiles.git"
      EOF

run_job:
  stage: run
  script:
    - chmod 755 .
    - ./init.sh --connection=local --skip-tags=ignore-ci
  interruptible: true
