- name: Create groups for {{ username }}
  group:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - cron

- name: Create user {{ username }}
  user:
    name: "{{ username }}"
    groups:
      - sudo
      - cron
      - docker
    system: true
    createhome: true
    home: "/home/{{ username }}"
